# Generated by Django 2.0.4 on 2018-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('text', models.TextField(blank=True, null=True)),
                ('section', models.CharField(choices=[('portrait', 'portrait'), ('city', 'city'), ('daily', 'daily')], max_length=200, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
